import { Button, Card, Form, Input, Modal, Popconfirm, Space, Tabs, Tag, message } from 'antd';
import { useEffect, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { api } from '../../api';
import { Page } from '../../components/common/Page';
import { MyCommentList } from '../../components/user/MyCommentList';
import { MyProfileHeroCard } from '../../components/user/MyProfileHeroCard';
import { MyProfileGrowthCard } from '../../components/user/MyProfileGrowthCard';
import { PostCard } from '../../components/post/PostCard';
import { useAuthStore } from '../../store/authStore';
import { postStatusColor, postStatusText } from '../../utils';
import type { Post } from '../../types';

export function MyProfilePage(){const {currentUser,setCurrentUser}=useAuthStore();const [params,setParams]=useSearchParams();const tab=params.get('tab')||'posts';const [posts,setPosts]=useState<Post[]>([]);const [editOpen,setEditOpen]=useState(false);const [form]=Form.useForm();async function loadPosts(){const r=await api.getPosts({page:1,pageSize:100,includeHidden:true,status:'all'});setPosts(r.list.filter(p=>p.authorId===currentUser?.userId));}useEffect(()=>{if(['posts','reposts','likes','favorites'].includes(tab))loadPosts()},[tab,currentUser]);if(!currentUser)return null;async function checkIn(){const r=await api.checkIn();message.success(`签到成功，获得 ${r.points} 积分`);setCurrentUser({...currentUser,checkedInToday:true,points:currentUser.points+r.points,continuousCheckInDays:r.continuousDays})}async function hide(p:Post){await api.hidePost(p.postId);message.success('已隐藏');loadPosts()}async function unhide(p:Post){await api.unhidePost(p.postId);message.success('已取消隐藏');loadPosts()}return <Page narrow><MyProfileHeroCard user={currentUser} onEdit={()=>{form.setFieldsValue(currentUser);setEditOpen(true)}}/><MyProfileGrowthCard user={currentUser} onCheckIn={checkIn}/><Card className="soft-card"><Tabs activeKey={tab} onChange={k=>setParams({tab:k})} items={[{key:'posts',label:'我的帖子'},{key:'reposts',label:'我的转发'},{key:'comments',label:'我的评论'},{key:'likes',label:'我的点赞'},{key:'favorites',label:'我的收藏'},{key:'badges',label:'我的勋章'}]}/>{tab==='comments'&&<MyCommentList/>}{tab==='badges'&&<Space wrap><Card className="badge-card"><h1>🥇</h1><Tag color="gold">首次发帖</Tag><p>发布第一篇帖子后获得。</p></Card><Card className="badge-card"><h1>🔥</h1><Tag color="red">人气作者</Tag><p>累计获得 1000 个点赞。</p></Card></Space>}{['posts','reposts','likes','favorites'].includes(tab)&&<div className="list-stack">{posts.filter(p=>tab==='reposts'?p.postType==='repost':tab==='likes'?p.liked:tab==='favorites'?p.favorited:p.postType==='original').map(p=><Card key={p.postId} className="soft-card my-post-card"><Space className="toolbar-space"><Tag color={postStatusColor[p.status]}>{postStatusText[p.status]}</Tag><Space>{p.status==='hidden'?<Popconfirm title="确认取消隐藏帖子？" onConfirm={()=>unhide(p)}><Button size="small">取消隐藏</Button></Popconfirm>:<Popconfirm title="确认隐藏帖子？" description="隐藏后不在公开内容流展示。" onConfirm={()=>hide(p)}><Button size="small">隐藏</Button></Popconfirm>}<Button size="small" href={`/posts/${p.postId}`}>查看</Button></Space></Space><PostCard post={p} mine onChange={(patch)=>setPosts(list=>list.map(x=>x.postId===p.postId?{...x,...patch}:x))}/></Card>)}</div>}</Card><Modal title="编辑资料" open={editOpen} onCancel={()=>setEditOpen(false)} onOk={()=>{const v=form.getFieldsValue();setCurrentUser({...currentUser,...v});setEditOpen(false);message.success('保存成功')}}><Form form={form} layout="vertical"><Form.Item name="nickname" label="昵称"><Input/></Form.Item><Form.Item name="bio" label="简介"><Input.TextArea rows={3}/></Form.Item></Form></Modal></Page>}
