import { AppstoreAddOutlined, AuditOutlined, BellOutlined, BookOutlined, CommentOutlined, DashboardOutlined, FlagOutlined, GiftOutlined, HomeOutlined, KeyOutlined, LogoutOutlined, ReadOutlined, RobotOutlined, SearchOutlined, SettingOutlined, TagsOutlined, TeamOutlined, TrophyOutlined } from '@ant-design/icons';
import { Avatar, Button, Layout, Menu, Space } from 'antd';
import { Navigate, Outlet, useLocation, useNavigate } from 'react-router-dom';
import { useAuthStore } from '../../store/authStore';

const { Sider, Header, Content } = Layout;
const items = [
  { key: '/admin', label: '数据看板', icon: <DashboardOutlined /> }, { key: '/admin/users', label: '用户管理', icon: <TeamOutlined /> }, { key: '/admin/posts', label: '帖子管理', icon: <BookOutlined /> }, { key: '/admin/comments', label: '评论管理', icon: <CommentOutlined /> }, { key: '/admin/reviews', label: '审核管理', icon: <AuditOutlined /> }, { key: '/admin/reports', label: '举报管理', icon: <FlagOutlined /> }, { key: '/admin/tags', label: '标签管理', icon: <TagsOutlined /> }, { key: '/admin/circles', label: '圈子管理', icon: <TeamOutlined /> }, { key: '/admin/topics', label: '话题管理', icon: <ReadOutlined /> }, { key: '/admin/search', label: '搜索管理', icon: <SearchOutlined /> }, { key: '/admin/recommend', label: '推荐管理', icon: <AppstoreAddOutlined /> }, { key: '/admin/points', label: '积分等级', icon: <TrophyOutlined /> }, { key: '/admin/badges', label: '勋章管理', icon: <GiftOutlined /> }, { key: '/admin/tasks', label: '任务管理', icon: <SettingOutlined /> }, { key: '/admin/activities', label: '活动管理', icon: <BellOutlined /> }, { key: '/admin/banners', label: '推荐位管理', icon: <AppstoreAddOutlined /> }, { key: '/admin/announcements', label: '官方公告', icon: <BookOutlined /> }, { key: '/admin/sensitive-words', label: '敏感词管理', icon: <SearchOutlined /> }, { key: '/admin/logs', label: '操作日志', icon: <DashboardOutlined /> }, { key: '/admin/operation-dashboard', label: '运营数据看板', icon: <DashboardOutlined /> }, { key: '/admin/ai/models', label: '基础模型管理', icon: <RobotOutlined /> }, { key: '/admin/ai/token-config', label: 'Token 配置', icon: <KeyOutlined /> },
];
export function AdminLayout() {
  const { currentUser, isLogin, logout } = useAuthStore(); const navigate = useNavigate(); const location = useLocation();
  if (!isLogin || currentUser?.role !== 'admin') return <Navigate to="/login" replace />;
  const selected = [...items].sort((a,b)=>b.key.length-a.key.length).find(i => location.pathname === i.key || (i.key !== '/admin' && location.pathname.startsWith(i.key)))?.key || '/admin';
  return <Layout className="admin-layout"><Sider width={240} className="admin-sider"><div className="admin-brand">社区后台</div><Menu mode="inline" selectedKeys={[selected]} items={items} onClick={({key})=>navigate(key)} className="admin-menu" /><Button className="back-front-btn" icon={<HomeOutlined />} onClick={()=>navigate('/')}>返回前台</Button></Sider><Layout><Header className="admin-header"><b>增强版社区管理台</b><Space><Avatar src={currentUser.avatar} />{currentUser.nickname}<Button icon={<LogoutOutlined />} onClick={()=>{logout();navigate('/login')}}>退出</Button></Space></Header><Content className="admin-content"><Outlet /></Content></Layout></Layout>;
}
