import { Button, Card, Form, Input, Modal, Select, Space, Table, Tag, message } from 'antd';
import { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import { api } from '../../api';
import { Page } from '../../components/common/Page';
import { roleText, statusText } from '../../utils';
import type { CircleJoinRequest, CircleMember } from '../../types';

export function CircleMemberManagePage(){const id=Number(useParams().circleId);const [members,setMembers]=useState<CircleMember[]>([]);const [requests,setRequests]=useState<CircleJoinRequest[]>([]);const [muteTarget,setMuteTarget]=useState<CircleMember>();const [form]=Form.useForm();async function load(){setMembers((await api.getCircleMembers(id)).list);setRequests(await api.getJoinRequests(id))}useEffect(()=>{load()},[id]);async function mute(){const v=await form.validateFields();await api.muteMember(id,muteTarget!.userId,v.duration,v.reason);message.success('已禁言');setMuteTarget(undefined);load()}return <Page><Card className="soft-card" title="圈子成员管理"><Table rowKey="id" dataSource={members} pagination={{pageSize:10}} columns={[{title:'成员',render:(_,m)=><Space><img src={m.user.avatar} className="mini-avatar"/><div><b>{m.user.nickname}</b><br/><span>加入时间：{m.joinedAt}</span></div></Space>},{title:'身份 / 状态',render:(_,m)=><Space><Tag color={m.role==='owner'?'gold':m.role==='member'?'default':'blue'}>{roleText[m.role]}</Tag><Tag color={m.status==='muted'?'red':'green'}>{statusText[m.status]}</Tag></Space>},{title:'操作',render:(_,m)=><Space wrap>{m.role==='member'&&<Button size="small" onClick={()=>api.setMemberRole(id,m.userId,'moderator').then(load)}>设为管理员</Button>}{m.status==='muted'?<Button size="small" onClick={()=>Modal.confirm({title:'确认解除禁言？',content:'解除后该成员可以继续在圈子内发帖、评论、聊天。',onOk:()=>api.unmuteMember(id,m.userId).then(load),okText:'确认解除',cancelText:'取消'})}>解除禁言</Button>:<Button size="small" onClick={()=>{setMuteTarget(m);form.setFieldsValue({duration:'7 天后'})}}>禁言</Button>}<Button danger size="small" onClick={()=>api.removeMember(id,m.userId).then(load)}>踢出</Button></Space>}]} /></Card><Card className="soft-card" title="加入申请"><Table rowKey="requestId" dataSource={requests} pagination={false} columns={[{title:'申请人',render:(_,r)=><Space><img src={r.user.avatar} className="mini-avatar"/>{r.user.nickname}</Space>},{title:'申请理由',dataIndex:'reason'},{title:'申请时间',dataIndex:'createdAt'},{title:'操作',render:(_,r)=><Space><Button type="primary" size="small" onClick={()=>api.handleJoinRequest(r.requestId,'approved').then(load)}>通过</Button><Button danger size="small" onClick={()=>api.handleJoinRequest(r.requestId,'rejected').then(load)}>拒绝</Button></Space>}]} /></Card><Modal title="禁言成员" open={!!muteTarget} onCancel={()=>setMuteTarget(undefined)} onOk={mute} okText="确认禁言" maskClosable={false}><Form form={form} layout="vertical" initialValues={{duration:'7 天后'}}><Form.Item label="成员">{muteTarget?.user.nickname}</Form.Item><Form.Item name="duration" label="禁言时长"><Select options={['1 天后','7 天后','30 天后','永久'].map(v=>({value:v,label:v}))}/></Form.Item><Form.Item name="reason" label="禁言原因" rules={[{required:true,message:'请输入禁言原因'}]}><Input.TextArea rows={3}/></Form.Item></Form></Modal></Page>}
