import { Card, DatePicker, Form, Input, Radio, Select, Button, Space, message } from 'antd';
import dayjs from 'dayjs';
import { useEffect, useState } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { api } from '../../api';
import { Page } from '../../components/common/Page';
import type { Circle, ContentTag, Topic } from '../../types';

export function PostCreatePage(){
  const [params]=useSearchParams(); const navigate=useNavigate(); const [form]=Form.useForm(); const circleId=Number(params.get('circleId'))||undefined; const sourceType=params.get('sourceType'); const noteId=Number(params.get('noteId'))||undefined; const answer=params.get('answer');
  const [circle,setCircle]=useState<Circle>(); const [circles,setCircles]=useState<Circle[]>([]); const [tags,setTags]=useState<ContentTag[]>([]); const [topics,setTopics]=useState<Topic[]>([]); const mode=Form.useWatch('publishMode',form);
  useEffect(()=>{api.getTags().then(setTags); api.getTopics({page:1,pageSize:50}).then(r=>setTopics(r.list)); api.getCircles({page:1,pageSize:50,scope:'joined'}).then(r=>setCircles(r.list)); if(circleId) api.getCircle(circleId).then(c=>{setCircle(c); form.setFieldsValue({circleId,visibility:'circle_only'})}); if(noteId) api.getNote(noteId).then(n=>form.setFieldsValue({title:n.title,content:n.content})); if(answer) form.setFieldsValue({title:'AI 回答整理',content:answer});},[circleId,noteId,answer]);
  async function submit(saveDraft=false){const v=await form.validateFields(); if(!v.tagIds?.length&&!saveDraft){message.warning('请至少选择一个内容标签');return;} const p=await api.createPost({title:v.title,content:v.content,images:v.images||[],tagIds:v.tagIds||[],topicIds:v.topicIds||[],circleId:circleId||v.circleId,visibility:v.visibility||'public',publishMode:saveDraft?'draft':v.publishMode,scheduledAt:v.scheduledAt?.format('YYYY-MM-DD HH:mm:ss')}); message.success(saveDraft?'草稿已保存':p.status==='scheduled'?'已设置定时发布':'发布成功'); navigate(p.status==='published'?`/posts/${p.postId}`:'/users/me?tab=posts');}
  return <Page narrow><Card className="soft-card" title="发布帖子"><Form form={form} layout="vertical" initialValues={{publishMode:'now',visibility:circleId?'circle_only':'public',tagIds:[],topicIds:[],images:[]}}>{circleId&&circle?<Card size="small" className="publish-circle-card">发布到：<b>{circle.name}</b></Card>:<Form.Item name="circleId" label="发布位置"><Select allowClear placeholder="不发布到圈子" options={circles.map(c=>({value:c.circleId,label:c.name}))}/></Form.Item>}{circleId?<Form.Item name="visibility" label="可见范围"><Radio.Group options={[{value:'circle_only',label:'圈子内可见'},{value:'public',label:'全站可见'}]}/></Form.Item>:<Form.Item name="visibility" label="可见范围"><Radio.Group options={[{value:'public',label:'全站可见'}]}/></Form.Item>}<Form.Item name="title" label="标题" rules={[{required:true,message:'请输入标题'},{min:5,message:'标题不能少于 5 个字'}]}><Input showCount maxLength={100}/></Form.Item><Form.Item name="content" label="正文" rules={[{required:true,message:'请输入正文'},{min:10,message:'正文不能少于 10 个字'}]}><Input.TextArea rows={10} maxLength={5000} showCount/></Form.Item><Form.Item name="tagIds" label="内容标签"><Select mode="multiple" maxCount={5} options={tags.map(t=>({value:t.tagId,label:t.tagName}))}/></Form.Item><Form.Item name="topicIds" label="关联话题"><Select mode="multiple" maxCount={3} options={topics.map(t=>({value:t.topicId,label:`#${t.name}#`}))}/></Form.Item><Form.Item name="publishMode" label="发布时间"><Radio.Group options={[{value:'now',label:'立即发布'},{value:'schedule',label:'定时发布'}]}/></Form.Item>{mode==='schedule'&&<Form.Item name="scheduledAt" label="定时发布时间" rules={[{required:true,message:'请选择发布时间'}]}><DatePicker showTime disabledDate={(d)=>d&&d.isBefore(dayjs(),'day')} style={{width:'100%'}}/></Form.Item>}<div className="form-actions"><Space><Button onClick={()=>submit(true)}>保存草稿</Button><Button type="primary" onClick={()=>submit(false)}>发布</Button></Space></div></Form></Card></Page>;
}
