import { Avatar, Button, Card, Form, Input, InputNumber, Modal, Radio, Select, Space, Table, Tag, message } from 'antd';
import { useEffect, useState } from 'react';
import { api, baseModels, tokenUsages, tokenConfig, users, posts, circles, topics, tags, activities, officialAnnouncements, banners } from '../../api';
import { Page } from '../../components/common/Page';
import type { BaseModel, TokenConfig } from '../../types';

export function AdminDashboardPage(){const [s,setS]=useState<any>();useEffect(()=>{api.adminStats().then(setS)},[]);return <Page><div className="metric-grid"><Card>今日新增用户<h2>{s?.todayNewUserCount}</h2></Card><Card>今日发帖数<h2>{s?.todayPostCount}</h2></Card><Card>今日评论数<h2>{s?.todayCommentCount}</h2></Card><Card>待审核<h2>{s?.pendingReviewCount}</h2></Card></div><Card className="soft-card" title="快捷入口"><Space wrap><Button href="/admin/posts">帖子管理</Button><Button href="/admin/circles">圈子管理</Button><Button href="/admin/ai/models">AI 配置</Button></Space></Card></Page>}
export function AdminUserPage(){return <Page><Card className="soft-card" title="用户管理"><Table rowKey="userId" dataSource={users} columns={[{title:'用户',render:(_,u)=><Space><Avatar src={u.avatar}/>{u.nickname}</Space>},{title:'角色',dataIndex:'role'},{title:'状态',dataIndex:'status'},{title:'发帖数',dataIndex:'postCount'},{title:'操作',render:()=> <Space><Button size="small">禁言</Button><Button size="small" danger>封禁</Button></Space>}]} /></Card></Page>}
export function AdminPostPage(){return <Page><Card className="soft-card" title="帖子管理"><Table rowKey="postId" dataSource={posts} columns={[{title:'标题',dataIndex:'title'},{title:'作者',render:(_,p)=>p.author.nickname},{title:'状态',dataIndex:'status'},{title:'点赞',dataIndex:'likeCount'},{title:'操作',render:()=> <Space><Button size="small">审核通过</Button><Button size="small" danger>下架</Button></Space>}]} /></Card></Page>}
export function AdminCommentPage(){return <Page><Card className="soft-card" title="评论管理"><Table dataSource={[]} columns={[{title:'评论ID'},{title:'帖子ID'},{title:'评论人'},{title:'内容'},{title:'操作'}]} /></Card></Page>}
export function AdminReviewPage(){return <Page><Card className="soft-card" title="审核管理"><p>待审核帖子、评论、圈子统一在这里处理。</p><Table dataSource={posts.filter(p=>p.status==='reviewing')} rowKey="postId" columns={[{title:'内容ID',dataIndex:'postId'},{title:'内容摘要',dataIndex:'title'},{title:'提交人',render:(_,p)=>p.author.nickname},{title:'操作',render:()=> <Space><Button type="primary" size="small">通过</Button><Button danger size="small">拒绝</Button></Space>}]} /></Card></Page>}
export function AdminReportPage(){return <Page><Card className="soft-card" title="举报管理"><Table dataSource={[{id:1,user:'张三',target:'帖子',reason:'垃圾广告',status:'待处理'}]} rowKey="id" columns={[{title:'举报人',dataIndex:'user'},{title:'对象',dataIndex:'target'},{title:'原因',dataIndex:'reason'},{title:'状态',dataIndex:'status'},{title:'操作',render:()=> <Space><Button size="small">通过举报</Button><Button size="small">驳回</Button></Space>}]} /></Card></Page>}
export function AdminTagPage(){const [open,setOpen]=useState(false);return <Page><Card className="soft-card" title="标签管理" extra={<Button type="primary" onClick={()=>setOpen(true)}>新增标签</Button>}><Table rowKey="tagId" dataSource={tags} columns={[{title:'标签名称',dataIndex:'tagName'},{title:'描述',dataIndex:'description'},{title:'使用次数',dataIndex:'useCount'},{title:'状态',dataIndex:'status'},{title:'操作',render:()=> <Space><Button size="small">编辑</Button><Button size="small">禁用</Button></Space>}]} /></Card><Modal title="新增标签" open={open} onCancel={()=>setOpen(false)} onOk={()=>{message.success('保存成功');setOpen(false)}}><Input placeholder="标签名称"/></Modal></Page>}
export function AdminCirclePage(){return <Page><Card className="soft-card" title="圈子管理"><Table rowKey="circleId" dataSource={circles} columns={[{title:'圈子',render:(_,c)=><Space><Avatar src={c.avatar}/>{c.name}</Space>},{title:'创建人',render:(_,c)=>c.owner.nickname},{title:'成员数',dataIndex:'memberCount'},{title:'内容数',dataIndex:'postCount'},{title:'状态',dataIndex:'status'},{title:'操作',render:()=> <Space><Button size="small">推荐</Button><Button size="small" danger>关闭</Button></Space>}]} /></Card></Page>}
export function AdminTopicPage(){return <Page><Card className="soft-card" title="话题管理"><Table rowKey="topicId" dataSource={topics} columns={[{title:'话题',render:(_,t)=>`#${t.name}#`},{title:'简介',dataIndex:'description'},{title:'内容数',dataIndex:'postCount'},{title:'参与人数',dataIndex:'participantCount'},{title:'推荐',render:(_,t)=>t.isRecommended?<Tag color="blue">推荐</Tag>:'-'},{title:'操作',render:()=> <Space><Button size="small">编辑</Button><Button size="small">推荐</Button></Space>}]} /></Card></Page>}
export function AdminSearchPage(){return <Page><Card className="soft-card" title="搜索管理"><Table dataSource={[{id:1,keyword:'AI 编程助手',count:3200,status:'normal'}]} rowKey="id" columns={[{title:'关键词',dataIndex:'keyword'},{title:'搜索次数',dataIndex:'count'},{title:'状态',dataIndex:'status'},{title:'操作',render:()=> <Button size="small">屏蔽</Button>}]} /></Card></Page>}
export function AdminRecommendPage(){return <Page><Card className="soft-card" title="推荐管理"><Table dataSource={[{id:1,type:'post',title:'如何高效学习一门新的编程语言？',weight:100,status:'online'}]} rowKey="id" columns={[{title:'类型',dataIndex:'type'},{title:'标题',dataIndex:'title'},{title:'权重',dataIndex:'weight'},{title:'状态',dataIndex:'status'},{title:'操作',render:()=> <Button size="small">下线</Button>}]} /></Card></Page>}
export function AdminPointLevelPage(){return <Page><Card className="soft-card" title="积分等级管理"><Table dataSource={[{id:1,action:'每日签到',points:5,status:'enabled'},{id:2,action:'发布帖子',points:10,status:'enabled'}]} rowKey="id" columns={[{title:'行为',dataIndex:'action'},{title:'积分',dataIndex:'points'},{title:'状态',dataIndex:'status'}]} /></Card></Page>}
export function AdminBadgePage(){return <Page><Card className="soft-card" title="勋章管理"><Table dataSource={[{id:1,icon:'🥇',name:'首次发帖',condition:'发布第一篇帖子',status:'enabled'}]} rowKey="id" columns={[{title:'图标',dataIndex:'icon'},{title:'名称',dataIndex:'name'},{title:'获得条件',dataIndex:'condition'},{title:'状态',dataIndex:'status'}]} /></Card></Page>}
export function AdminTaskPage(){return <Page><Card className="soft-card" title="任务管理"><Table dataSource={[{id:1,title:'完善个人资料',type:'newbie',reward:20,status:'enabled'}]} rowKey="id" columns={[{title:'任务名称',dataIndex:'title'},{title:'类型',dataIndex:'type'},{title:'奖励',dataIndex:'reward'},{title:'状态',dataIndex:'status'}]} /></Card></Page>}
export function AdminActivityPage(){return <Page><Card className="soft-card" title="活动管理"><Table rowKey="activityId" dataSource={activities} columns={[{title:'活动名称',dataIndex:'title'},{title:'类型',dataIndex:'type'},{title:'参与人数',dataIndex:'participantCount'},{title:'状态',dataIndex:'status'},{title:'操作',render:()=> <Space><Button size="small">查看数据</Button><Button size="small">下线</Button></Space>}]} /></Card></Page>}
export function AdminBannerPage(){return <Page><Card className="soft-card" title="推荐位管理"><Table rowKey="bannerId" dataSource={banners} columns={[{title:'标题',dataIndex:'title'},{title:'跳转链接',dataIndex:'targetUrl'},{title:'权重',dataIndex:'weight'},{title:'状态',dataIndex:'status'}]} /></Card></Page>}
export function AdminAnnouncementPage(){return <Page><Card className="soft-card" title="官方公告管理"><Table rowKey="announcementId" dataSource={officialAnnouncements} columns={[{title:'标题',dataIndex:'title'},{title:'发布人',dataIndex:'publisherName'},{title:'状态',dataIndex:'status'},{title:'发布时间',dataIndex:'publishedAt'}]} /></Card></Page>}
export function AdminSensitiveWordPage(){return <Page><Card className="soft-card" title="敏感词管理"><Table dataSource={[{id:1,word:'广告引流',strategy:'审核',status:'启用'}]} rowKey="id" columns={[{title:'敏感词',dataIndex:'word'},{title:'策略',dataIndex:'strategy'},{title:'状态',dataIndex:'status'}]} /></Card></Page>}
export function AdminOperationLogPage(){const [data,setData]=useState<any[]>([]);useEffect(()=>{api.getAdminLogs({page:1,pageSize:20}).then(r=>setData(r.list))},[]);return <Page><Card className="soft-card" title="操作日志"><Table rowKey="logId" dataSource={data} columns={[{title:'管理员',dataIndex:'adminName'},{title:'操作类型',dataIndex:'action'},{title:'对象类型',dataIndex:'targetType'},{title:'操作说明',dataIndex:'detail'},{title:'时间',dataIndex:'createdAt'}]} /></Card></Page>}
export function AdminOperationDashboardPage(){return <Page><div className="metric-grid"><Card>DAU<h2>2680</h2></Card><Card>新增用户<h2>128</h2></Card><Card>发帖数<h2>256</h2></Card><Card>活动参与人数<h2>3450</h2></Card></div><Card className="soft-card" title="活动数据"><Table dataSource={[{id:1,name:'AI 编程助手实践',expose:12000,participants:2345,rate:'19.5%'}]} rowKey="id" columns={[{title:'活动名称',dataIndex:'name'},{title:'曝光数',dataIndex:'expose'},{title:'参与人数',dataIndex:'participants'},{title:'转化率',dataIndex:'rate'}]}/></Card></Page>}
export function AdminAiModelPage(){const [list,setList]=useState<BaseModel[]>(baseModels);const [open,setOpen]=useState(false);const [editing,setEditing]=useState<BaseModel>();const [form]=Form.useForm();function save(){const v=form.getFieldsValue();api.saveBaseModel({...editing,...v}).then(()=>{setList([...baseModels]);setOpen(false);message.success('保存成功')})}return <Page><Card className="soft-card" title="基础模型管理" extra={<Button type="primary" onClick={()=>{setEditing(undefined);form.resetFields();setOpen(true)}}>新增模型</Button>}><Table rowKey="modelId" dataSource={list} columns={[{title:'供应商',dataIndex:'providerName'},{title:'模型名称',dataIndex:'modelName'},{title:'Base URL',dataIndex:'baseUrl'},{title:'默认',render:(_,m)=>m.isDefault?'是':'否'},{title:'状态',dataIndex:'status'},{title:'操作',render:(_,m)=><Space><Button size="small" onClick={()=>{setEditing(m);form.setFieldsValue(m);setOpen(true)}}>编辑</Button><Button size="small" onClick={()=>api.setDefaultModel(m.modelId).then(()=>setList([...baseModels]))}>设为默认</Button><Button size="small" onClick={()=>api.setModelStatus(m.modelId,m.status==='enabled'?'disabled':'enabled').then(()=>setList([...baseModels]))}>{m.status==='enabled'?'禁用':'启用'}</Button></Space>}]} /></Card><Modal title={editing?'编辑模型':'新增模型'} open={open} onCancel={()=>setOpen(false)} onOk={save} maskClosable={false}><Form form={form} layout="vertical" initialValues={{provider:'deepseek',providerName:'DeepSeek',status:'enabled'}}><Form.Item name="providerName" label="供应商" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="modelName" label="模型名称" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="baseUrl" label="Base URL" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="isDefault" label="是否平台默认"><Radio.Group options={[{value:true,label:'是'},{value:false,label:'否'}]}/></Form.Item><Form.Item name="status" label="状态"><Select options={[{value:'enabled',label:'启用'},{value:'disabled',label:'禁用'}]}/></Form.Item></Form></Modal></Page>}
export function AdminAiTokenConfigPage(){const [form]=Form.useForm<TokenConfig>();const [usages,setUsages]=useState(tokenUsages);useEffect(()=>{form.setFieldsValue(tokenConfig)},[]);function save(){api.saveTokenConfig(form.getFieldsValue()).then(()=>message.success('Token 配置已保存'))}return <Page><Card className="soft-card" title="Token 配置"><Form form={form} layout="vertical"><Form.Item name="dailyMaxTokens" label="每日最大 Token" rules={[{required:true}]}><InputNumber min={1}/></Form.Item><Form.Item name="userDailyMaxTokens" label="单用户每日最大 Token"><InputNumber min={1}/></Form.Item><Form.Item name="singleConversationMaxTokens" label="单次对话最大 Token"><InputNumber min={1}/></Form.Item><Form.Item name="overLimitStrategy" label="超限策略"><Radio.Group options={[{value:'reject',label:'拒绝调用'},{value:'downgrade',label:'降级模型'},{value:'warn',label:'仅提醒'}]}/></Form.Item><Button type="primary" onClick={save}>保存配置</Button></Form></Card><Card className="soft-card" title="用户 Token 使用情况"><Table rowKey="userId" dataSource={usages} columns={[{title:'用户',render:(_,u)=><Space><Avatar src={u.avatar}/>{u.nickname}</Space>},{title:'今日已用 Token',dataIndex:'todayTokens'},{title:'本月已用 Token',dataIndex:'monthTokens'},{title:'最后调用时间',dataIndex:'lastUsedAt'},{title:'操作',render:(_,u)=><Button size="small" onClick={()=>api.resetUserTokens(u.userId).then(()=>setUsages([...tokenUsages]))}>重置今日额度</Button>}]} /></Card></Page>}
