import { Button, Card, Input, Select, Space, Tabs, Tag, Typography, message } from 'antd';
import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { api } from '../../api';
import { Page } from '../../components/common/Page';
import { EmptyState } from '../../components/common/States';
import type { Circle, CircleScopeTab, PageResult } from '../../types';

export function CircleListPage(){const nav=useNavigate();const [scope,setScope]=useState<CircleScopeTab>('all');const [keyword,setKeyword]=useState('');const [data,setData]=useState<PageResult<Circle>>();async function load(){setData(await api.getCircles({page:1,pageSize:50,scope,keyword}))}useEffect(()=>{load()},[scope,keyword]);async function join(c:Circle){const r=await api.joinCircle(c.circleId);message.success(r.pending?'申请已提交，请等待审核':'加入圈子成功');load()}return <Page><Card className="soft-card page-title-card"><div><Typography.Title level={2}>发现圈子</Typography.Title><Typography.Text type="secondary">加入感兴趣的社区空间，和同好一起交流。</Typography.Text></div><Button type="primary" onClick={()=>nav('/circles/create')}>创建圈子</Button></Card><Card className="soft-card"><Tabs activeKey={scope} onChange={v=>setScope(v as CircleScopeTab)} items={[{key:'all',label:'全部圈子'},{key:'recommended',label:'推荐圈子'},{key:'joined',label:'我加入的圈子'},{key:'created',label:'我创建的圈子'}]}/><Input.Search placeholder="搜索圈子" onSearch={setKeyword} allowClear style={{maxWidth:260,marginBottom:16}}/>{data?.list.length===0?<EmptyState description={scope==='created'?'你还没有创建圈子，去创建一个吧':'暂无相关圈子'} actionText={scope==='created'?'创建圈子':undefined} onAction={()=>nav('/circles/create')}/>:<div className="circle-grid">{data?.list.map(c=><Card key={c.circleId} className="soft-card circle-card" hoverable onClick={()=>nav(`/circles/${c.circleId}`)}><Space align="start"><img src={c.avatar} className="circle-avatar"/><div><Typography.Title level={4}>{c.name}</Typography.Title><Typography.Paragraph ellipsis={{rows:2}}>{c.description}</Typography.Paragraph><Space wrap>{c.tags.map(t=><Tag key={t.tagId}>{t.tagName}</Tag>)}<Tag color={c.status==='normal'?'green':'red'}>{c.status==='normal'?'正常':c.status}</Tag></Space><p>{c.memberCount} 成员 · {c.postCount} 内容 · {c.featuredPostCount} 精华</p><Space><Button type="primary" onClick={e=>{e.stopPropagation();c.isJoined?nav(`/circles/${c.circleId}`):join(c)}}>{c.isJoined?'进入圈子':c.joinType==='approval'?'申请加入':'加入圈子'}</Button>{scope==='created'&&<Button onClick={e=>{e.stopPropagation();nav(`/circles/${c.circleId}/manage/members`)}}>管理圈子</Button>}</Space></div></Space></Card>)}</div>}</Card></Page>}
